# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tinysong}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dale Campbell"]
  s.date = %q{2010-06-22}
  s.description = %q{TinySong Ruby library.}
  s.email = %q{oshuma@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
     "README.rdoc",
     "Rakefile",
     "lib/grooveshark.rb",
     "lib/grooveshark/tiny_song.rb",
     "spec/grooveshark/tiny_song_spec.rb",
     "spec/spec_helper.rb",
     "watchr_suite.rb"
  ]
  s.homepage = %q{http://github.com/Oshuma/tiny_song}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{TinySong Ruby library.}
  s.test_files = [
    "spec/grooveshark/tiny_song_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

